baseURL: "https://erics.earth/"
title: Eric Taylor
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: home
          pageRef: /
          weight: 1
        - name: cv
          url: /Eric_Taylor_CV.pdf
          weight: 2
        - name: work
          pageRef: /projects
          weight: 3
        - name: play
          pageRef: /interests
          weight: 4
        - name: notes
          pageRef: /personal
          weight: 5


params:
    description: "Eric Taylor’s corner of the internet. Research, projects, interests, and notes."
    author: Eric Taylor
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    mainSections: ["projects", "interests", "personal"]
    hideAuthor: true
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    socialIcons:
        - name: CV
          url: Eric_Taylor_CV.pdf
        - name: Email
          url: mailto:eric.taylor@worc.ox.ac.uk
        - name: GitHub
          url: https://github.com/eric-taylor-geo
        # - name: Twitter
        #   url: https://x.com/EricLTaylor_
        - name: LinkedIn
          url: https://www.linkedin.com/in/eric-taylor-8a82a4201/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Eric Taylor"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2