baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Eric Taylor
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 3
        - name: Interests
          url: interests/
          weight: 4


params:
    description: "This website hosts Eric Taylor's information and projects."
    author: Eric Taylor
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Projects","Hobbies"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Eric Taylor
          subtitle: "I am an MSc student in Environmental Data Science and ML at Imperial. I recently graduated with a first-class Geography degree from the University of Cambridge. I have an interest in the remote sensing of debris-covered glaciers to better quantify their longevity under climate change. In my free time I enjoy running and re-creating real-world locations in Minecraft."
          imageUrl: "profile_picture.JPG"
          imageWidth: 160
          imageHeight: 160
          buttons:
            # - name: Papers
            #   url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            - name: Projects
              url: projects/
            - name: Interests
              url: interests/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/

    socialIcons:
        - name: CV
          url: Eric_Taylor_CV.pdf
        - name: Email
          url: mailto:elt25@ic.ac.uk
        - name: GitHub
          url: https://github.com/eric-taylor-geo
        - name: Twitter
          url: https://x.com/EricLTaylor_
        - name: LinkedIn
          url: https://www.linkedin.com/in/eric-taylor-8a82a4201/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Eric Taylor"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2